# Generated by Django 5.2.11 on 2026-03-07 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='cities/')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='projects/')),
                ('masterplan_image', models.ImageField(blank=True, null=True, upload_to='projects/masterplans/')),
                ('location', models.TextField(help_text='Location description')),
                ('area', models.CharField(help_text='Total area/space of the project', max_length=255)),
                ('building_ratio', models.CharField(blank=True, help_text='e.g. 50%, 35%', max_length=100, null=True)),
                ('composition', models.CharField(blank=True, help_text='e.g. residential/hotel, commercial/admin/residential', max_length=255, null=True)),
                ('floors', models.CharField(blank=True, help_text='e.g. Basement + ground + 3 floors', max_length=255, null=True)),
                ('unit_sizes', models.CharField(blank=True, help_text='e.g. (45 : 127) m²', max_length=255, null=True)),
                ('payment_plan', models.TextField(blank=True, help_text='Payment plan details', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.city')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
