# Generated by Django 5.2.11 on 2026-03-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_tag_id', models.CharField(blank=True, help_text='Google Tag Manager ID (e.g. GTM-XXXXXXX)', max_length=50, null=True)),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics Measurement ID (e.g. G-XXXXXXXXXX)', max_length=50, null=True)),
                ('facebook_pixel_id', models.CharField(blank=True, help_text='Facebook Pixel ID (e.g. 123456789012345)', max_length=50, null=True)),
                ('tiktok_pixel_id', models.CharField(blank=True, help_text='TikTok Pixel ID (e.g. CXXXXXXXXXXXXXXXXX)', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
